CREATE TABLE IF NOT EXISTS `shop` (
    id INT(10) NOT NULL AUTO_INCREMENT,
    thing_id VARCHAR(50),
    thing_count int(50),
    thing_name VARCHAR(50),
    thing_price bigint(50),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_delete int,
    is_one int,
    PRIMARY KEY (id)
    );