CREATE TABLE IF NOT EXISTS `user_bag` (
    id INT(10) NOT NULL AUTO_INCREMENT,
    wxid_id VARCHAR(50),
    entity_id VARCHAR(50),
    entity_name VARCHAR(50),
    entity_type VARCHAR(50),
    is_delete int,
    create_time TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    start_time TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    end_time TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    use_cout int,
    PRIMARY KEY (id)
    );