spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/webchat?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8"
    username: root
    password:
  jpa:
    show-sql: true

server:
    port: 8081

api:
    reply-interval: 1000
    wechat-url: "http://127.0.0.1:2022/KP"
    wechat-url-cat: "http://localhost:88/httpAPI"
    tuLing-api: "http://openapi.tuling123.com/openapi/api/v2"
    tuLing-api-key: "0dd580fb0128ac0f7584572c642ba312"
    tuLing-user-id: "xiaoxiao"
    Baidu-text-review: "https://aip.baidubce.com/rest/2.0/solution/v1/text_censor/v2/user_defined"
    source-voice-root-path: "G://微信群管家/可爱猫4.4.1含开发包/debug/可爱猫4.4.1含开发包/可爱猫4.4.0/data/temp"
    silk-v3-decoder-path: "G://test/pcm/bin/silk_v3_decoder.exe"
    ffmpeg-path: "G://test/pcm/bin/ffmpeg.exe"
    temp-data-file-path: "E://test"
    robotId: "wxid_i5vabkq7vwb222"
    robotName: "Robot"
    appFilePath: "G://test"
    minior:
      danmuOpen: false
      #liveId: 125853211144
      #zbId: Sy980317
      liveId: 334834206241
      zbId: 128165353
      # 用户集合
      # 2428182699715406 雪
      # 109318880836 狐狸
      # 62474263189 加
      # 76089173365 bo
      # 58688615767 三
      # 71091000991 偏执
      # 98481654073 剪辑君
      pythonFilePath: "M://爬抖音/DouyinLiveWebFetcher-main/DouyinLiveWebFetcher-main/minior.py"
      managerDouYId: "2428182699715406,109318880836,62474263189,76089173365,58688615767,71091000991,98481654073"
      notifyUrl: "https://www.jsdream.club/webChat/gzh/notify"
      signJsPath: "M://爬抖音/DouyinLiveWebFetcher-main/DouyinLiveWebFetcher-main/sign.js"
      nodeModulesPath: "M://爬抖音/DouyinLiveWebFetcher-main/DouyinLiveWebFetcher-main/node_modules"
      castLogPath: "M://爬抖音/DouyinLiveWebFetcher-main/DouyinLiveWebFetcher-main/log"
logging:
  config: classpath:log4j-spring.xml
Log4jContextSelector: org.apache.logging.log4j.core.async.AsyncLoggerContextSelector
